{% set name = "icechunk" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/earth-mover/icechunk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1ce24ecea0e0a20787df483c91f90fba396a91a7bcc801cb0c974b4aa3a8dda2

build:
  skip: true  # [py<311 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cd icechunk-python
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.7,<2.0  # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7,<2.0
    - poetry-core
    - pip
  run:
    - python
    - zarr >=3

test:
  imports:
    - icechunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/earth-mover/icechunk
  summary: Transactional storage engine for Zarr designed for use on cloud object storage
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - andersy005
    - dcherian
    - jhamman
    - mpiannucci
    - paraseba
    - rabernat
