schema_version: 1

context:
  name: icechunk
  version: "2.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/earth-mover/icechunk/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3bb8ccb9e17dbd98c9f9955e657af85cbfc3da8787652b9bc18ba547580e6f61

build:
  number: 1
  skip: match(python, "<3.12") or python_impl == 'pypy'
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cd icechunk-python
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: maturin >=1.7.0,<2.0
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
  run:
    - python
    - if: not aarch64
      then: zarr >=3.1

tests:
  - python:
      imports:
        - if: not aarch64
          then: icechunk
      pip_check: false
  - requirements:
      run:
        - if: not aarch64
          then: pip
    script:
      - if: not aarch64
        then: pip check

about:
  summary: Transactional storage engine for Zarr designed for use on cloud object storage
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/earth-mover/icechunk

extra:
  recipe-maintainers:
    - ianhi
    - li-em
    - TomNicholas
    - andersy005
    - dcherian
    - jhamman
    - mpiannucci
    - paraseba
    - rabernat
